name: Build and Deploy Docs

on:
  push:
    tags:
      - '*'
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
  workflow_dispatch:   # Allow manual triggering

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Check out repository
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      - uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5
        with:
          python-version: 3.x

      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV

      - uses: actions/cache@6849a6489940f00c2f30c0fb92c6274307ccb58a # v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - name: Install and Build
        if: github.event.action != 'closed'
        run: |
          cd docs
          pip install -r requirements.txt
          mkdocs build

      # Deploy with pr-preview only on PRs
      - name: Deploy preview
        if: github.event_name == 'pull_request'
        uses: rossjrw/pr-preview-action@430e3dfc1de8a8ae77e77d862d25676ef9db55d1 # v1
        with:
          token: ${{ secrets.DEPLOY_TOKEN }}
          custom-url: 4ctf.4ts.fr
          source-dir: ./docs/site
          
      - name: Deploy preview directory
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: JamesIves/github-pages-deploy-action@dc18a3c6b46d56484cb63f291becd7ed4f0269b9 # v4.7.1
        with:
          token: ${{ secrets.DEPLOY_TOKEN }}
          folder: ./docs/site
          commit-message: Deploy production site 🚀
          clean: true
          clean-exclude: .gitignore
          force: false
