name: Go Unit Tests

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

    - name: Set up Go
      uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4
      with:
        go-version: '1.23.3'

    - name: Install dependencies
      working-directory: ./back
      run: go get -v -t -d ./...

    - name: Run unit tests
      working-directory: ./back
      run: go test ./... -v
