name: Deploy Docs

on:
  push:
    branches:
      - gh-pages
  workflow_dispatch:   # Allow manual triggering

jobs:
  deployment:
    name: Deploy to production
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
    steps:
      - name: Create GitHub Deployment
        uses: actions/github-script@v5
        with:
          script: |
            const { data: deployment } = await github.repos.createDeployment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.ref,
              environment: "gh-pages",
              description: "Deployment to Self-Hosted GitHub Pages",
              auto_merge: false,
              required_contexts: []
            });

            console.log(`Created deployment: ${deployment.id}`);
            return deployment.id;

      - name: Deploy to production
        run: curl -X GET ${{ secrets.DEPLOY_URL }}

      - name: Update Deployment Status
        uses: actions/github-script@v5
        with:
          script: |
            await github.repos.createDeploymentStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              deployment_id: ${{ steps.create.outputs.result }},
              state: "success",
              environment_url: "https://4ctf.4ts.fr/",
              description: "Deployed to Self-Hosted GitHub Pages"
            });