name: Deploy Docs

on:
  push:
    branches:
      - gh-pages
  workflow_dispatch:   # Allow manual triggering

jobs:
  deployment:
    name: Deploy to production
    runs-on: self-hosted
    environment: gh-pages
    concurrency: gh-pages
    permissions:
      contents: read
      packages: write
    steps:
      - name: Deploy to production
        run: curl -X GET ${{ secrets.DEPLOY_URL }}

      - name: Report Success
        if: success()
        uses: actions/github-script@v2
        with:
          script: |
            const deployment = context.payload.deployment;

            await github.repos.createDeploymentStatus({
                ...context.repo,
                deployment_id: deployment.id,
                state: 'success',
                environment: "gh-pages",
                environment_url: "https://4ctf.4ts.fr/",
                log_url: `https://github.com/${process.env.GITHUB_REPOSITORY}/actions/runs/${process.env.GITHUB_RUN_ID}`,
                mediaType: {
                  previews: ['ant-man']},
            });