name: Deploy Docs

on:
  push:
    branches:
      - gh-pages
  workflow_dispatch:   # Allow manual triggering

jobs:
  deployment:
    name: Deploy to production
    runs-on: self-hosted
    # environment: gh-pages
    # concurrency: gh-pages
    permissions:
      contents: read
      packages: write
    steps:
      - name: Create Deployment
        id: create_deployment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Create a deployment
          response=$(curl -s -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/deployments \
            -d '{
              "ref": "'${{ github.ref }}'",
              "environment": "gh-pages",
              "description": "Deploying self-hosted pages",
              "auto_merge": false,
              "required_contexts": []
            }')
          echo $response | jq
          echo "deployment_id=$(echo $response | jq -r .id)" >> $GITHUB_ENV

      - name: Deploy Pages
        run: curl -X GET ${{ secrets.DEPLOY_URL }}

      - name: Update Deployment Status
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEPLOY_URL: https://4ctf.4ts.fr/
        run: |
          curl -s -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/deployments/${{ env.deployment_id }}/statuses \
            -d '{
              "state": "success",
              "environment": "gh-pages",
              "log_url": "'"${DEPLOY_URL}"'",
              "description": "Deployment successful",
              "environment_url": "'"${DEPLOY_URL}"'"
            }'