// Code generated by SQLBoiler 4.17.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	UserSessions string
	Users        string
}{
	UserSessions: "user_sessions",
	Users:        "users",
}
